--Se le solicita realizar los siguientes incisos:
--1. Consultar la cantidad de likes por publicación.
SELECT A.CODIGO_PUBLICACION, B.CONTENIDO_PUBLICACION, COUNT(*) AS CANTIDAD_LIKES
FROM TBL_LIKE_PUBLICACIONES A
INNER JOIN TBL_PUBLICACIONES B
ON A.CODIGO_PUBLICACION = B.CODIGO_PUBLICACION
GROUP BY A.CODIGO_PUBLICACION, B.CONTENIDO_PUBLICACION
ORDER BY 1;

--2. Consultar la cantidad de likes por fotografía.
SELECT A.CODIGO_FOTO, B.DESCRIPCION_FOTO, COUNT(*) AS CANTIDAD_LIKES
FROM TBL_LIKE_FOTOGRAFIAS A
INNER JOIN TBL_FOTOS B
ON A.CODIGO_FOTO = B.CODIGO_FOTO
GROUP BY A.CODIGO_FOTO, B.DESCRIPCION_FOTO
ORDER BY 1;

SELECT *
FROM TBL_FOTOS;

--3. Consultar los grupos en los cuales la cantidad de usuarios sea mayor que 5,
-- mostrar el nombre del grupo y la cantidad de usuarios.
SELECT *
FROM TBL_GRUPOS;

SELECT A.CODIGO_GRUPO, B.NOMBRE_GRUPO, COUNT(*) AS CANTIDAD_USUARIOS
FROM TBL_GRUPOS_X_USUARIO A
INNER JOIN TBL_GRUPOS B
ON A.CODIGO_GRUPO = B.CODIGO_GRUPO
GROUP BY A.CODIGO_GRUPO, B.NOMBRE_GRUPO
HAVING COUNT(*) > 5
ORDER BY A.CODIGO_GRUPO;

---
SELECT 
FROM
TABLAS
JOIN
WHERE
GROUP BY
HAVING
ORDER BY

-- 1-> 16
-- 2-> 20

--4. Mostrar la cantidad de amistades pendientes y rechazadas.
SELECT B.NOMBRE_ESTATUS, COUNT(*) AS CANTIDAD_AMISTADES
FROM TBL_AMIGOS A
INNER JOIN TBL_ESTATUS_SOLICITUDES B
ON A.CODIGO_ESTATUS = B.CODIGO_ESTATUS
WHERE A.CODIGO_ESTATUS IN (2,3)
GROUP BY B.NOMBRE_ESTATUS;

SELECT *
FROM TBL_ESTATUS_SOLICITUDES;

--5. Mostrar el usuario con mayor cantidad de amigos confirmados (El más cool).
SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_AMIGOS
FROM TBL_AMIGOS
WHERE CODIGO_ESTATUS = 1
GROUP BY CODIGO_USUARIO
ORDER BY CANTIDAD_AMIGOS DESC
FETCH FIRST 1 ROW ONLY;



SELECT *
FROM (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_AMIGOS
    FROM TBL_AMIGOS
    WHERE CODIGO_ESTATUS = 1
    GROUP BY CODIGO_USUARIO
    ORDER BY CANTIDAD_AMIGOS DESC
)
WHERE CANTIDAD_AMIGOS = (
    SELECT MAX(CANTIDAD_AMIGOS)
    FROM (
        SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_AMIGOS
        FROM TBL_AMIGOS
        WHERE CODIGO_ESTATUS = 1
        GROUP BY CODIGO_USUARIO
        ORDER BY CANTIDAD_AMIGOS DESC
    )
);

WITH AMIGOS_CONFIRMADOS AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_AMIGOS
    FROM TBL_AMIGOS
    WHERE CODIGO_ESTATUS = 1
    GROUP BY CODIGO_USUARIO
    ORDER BY CANTIDAD_AMIGOS DESC
)
SELECT A.CODIGO_USUARIO, B.NOMBRE_USUARIO, A.CANTIDAD_AMIGOS
FROM AMIGOS_CONFIRMADOS A
INNER JOIN TBL_USUARIOS B 
ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
WHERE CANTIDAD_AMIGOS = (
    SELECT MAX(CANTIDAD_AMIGOS)
    FROM AMIGOS_CONFIRMADOS
);


SELECT *
FROM TBL_ESTATUS_SOLICITUDES;

--6. Mostrar el usuario con más solicitudes rechazadas (Forever alone).
WITH SOLICITUDES_RECHAZADAS AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_RECHAZOS
    FROM TBL_AMIGOS
    WHERE CODIGO_ESTATUS = 2
    GROUP BY CODIGO_USUARIO
    ORDER BY CANTIDAD_RECHAZOS DESC
)
SELECT A.CODIGO_USUARIO,B.NOMBRE_USUARIO, A.CANTIDAD_RECHAZOS
FROM SOLICITUDES_RECHAZADAS A
INNER JOIN TBL_USUARIOS B 
ON A.CODIGO_USUARIO = B.CODIGO_USUARIO
WHERE CANTIDAD_RECHAZOS = (
    SELECT MAX(CANTIDAD_RECHAZOS)
    FROM SOLICITUDES_RECHAZADAS
);


--7. Mostrar la cantidad de usuarios registrados mensualmente.
SELECT  TO_CHAR(FECHA_REGISTRO, 'YYYY-Month') AS ANIO_MES,
        COUNT(*) AS CANTIDAD_USUARIOS
FROM TBL_USUARIOS
GROUP BY TO_CHAR(FECHA_REGISTRO, 'YYYY-Month')
ORDER BY ANIO_MES;


--8. Mostrar la edad promedio de los usuarios por género.
SELECT GENERO_USUARIO, ROUND(AVG(EDAD),2) AS EDAD_PROMEDIO
FROM TBL_USUARIOS
GROUP BY GENERO_USUARIO;


--9. Con respecto al historial de accesos se necesita saber el crecimiento de los accesos del día 19 de
--agosto del 2015 con respecto al día anterior, la fórmula para calcular dicho crecimiento se
--muestra a continuación:
--
--((b-a)/a) * 100
--
--Donde:
--a = Cantidad de accesos del día anterior (18 de Agosto del 2015)
--b = Cantidad de accesos del día actual (19 de Agosto del 2015)
--Mostrar el resultado como un porcentaje (Concatenar %)

SELECT COUNT(*) AS ACCESOS_DIA_ACTUAL
FROM TBL_HISTORIAL_ACCESOS
WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('19-08-2015','DD-MM-YYYY'));

SELECT COUNT(*) ACCESOS_DIA_ANTERIOR
FROM TBL_HISTORIAL_ACCESOS
WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('18-08-2015','DD-MM-YYYY'));

SELECT ((
        (
            SELECT COUNT(*) AS ACCESOS_DIA_ACTUAL
            FROM TBL_HISTORIAL_ACCESOS
            WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('19-08-2015','DD-MM-YYYY'))
        ) - (
            SELECT COUNT(*) ACCESOS_DIA_ANTERIOR
            FROM TBL_HISTORIAL_ACCESOS
            WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('18-08-2015','DD-MM-YYYY'))
        )) / (
            SELECT COUNT(*) ACCESOS_DIA_ANTERIOR
            FROM TBL_HISTORIAL_ACCESOS
            WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('18-08-2015','DD-MM-YYYY'))
        )) * 100 || '%' AS CRECIMIENTO
FROM DUAL;

WITH B AS (
    SELECT COUNT(*) AS ACCESOS_DIA_ACTUAL
    FROM TBL_HISTORIAL_ACCESOS
    WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('19-08-2015','DD-MM-YYYY'))
),
A AS (
    SELECT COUNT(*) ACCESOS_DIA_ANTERIOR
    FROM TBL_HISTORIAL_ACCESOS
    WHERE TRUNC(FECHA_HORA_ACCESO) = TRUNC(TO_DATE('18-08-2015','DD-MM-YYYY'))
)
SELECT ((b.ACCESOS_DIA_ACTUAL-a.ACCESOS_DIA_ANTERIOR)/a.ACCESOS_DIA_ANTERIOR) * 100 || '%' AS CRECIMIENTO
FROM A, B;


--10. Crear una consulta que muestre lo siguiente:
--• Nombre del usuario.
--• País donde pertenece.
--• Cantidad de publicaciones que tiene.
--• Cantidad de amigos confirmados.
--Cantidad de likes que ha dado.
--• Cantidad de fotos en las que ha sido etiquetado.
--• Cantidad de accesos en el historial.
--Tip: utilice subconsultas.

SELECT * --30
FROM TBL_USUARIOS;

CREATE MATERIALIZED VIEW MVW_USUARIOS AS 
WITH PUBLICACIONES AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_PUBLICACIONES
    FROM TBL_PUBLICACIONES
    GROUP BY CODIGO_USUARIO
),
AMIGOS AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_AMIGOS
    FROM TBL_AMIGOS
    WHERE CODIGO_ESTATUS = 1
    GROUP BY CODIGO_USUARIO
),
LIKES_PUBLICACIONES AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS LIKES_PUBLICACIONES
    FROM TBL_LIKE_PUBLICACIONES
    GROUP BY CODIGO_USUARIO
),
LIKES_FOTOGRAFIAS AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS LIKES_FOTOS
    FROM TBL_LIKE_FOTOGRAFIAS
    GROUP BY CODIGO_USUARIO
),
ETIQUETAS_FOTOS AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_ETIQUETAS
    FROM TBL_ETIQUETA_FOTOGRAFIAS
    GROUP BY CODIGO_USUARIO
),
ACCESOS AS (
    SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_ACCESOS 
    FROM TBL_HISTORIAL_ACCESOS
    GROUP BY CODIGO_USUARIO
)
SELECT  A.CODIGO_USUARIO,
        A.NOMBRE_USUARIO,
        B.NOMBRE_PAIS,
        NVL(C.CANTIDAD_PUBLICACIONES, 0) AS CANTIDAD_PUBLICACIONES,
        NVL(D.CANTIDAD_AMIGOS, 0) AS CANTIDAD_AMIGOS,
        NVL(E.LIKES_PUBLICACIONES, 0) AS LIKES_PUBLICACIONES,
        NVL(F.LIKES_FOTOS, 0) AS LIKES_FOTOS,
        NVL(E.LIKES_PUBLICACIONES, 0) + NVL(F.LIKES_FOTOS, 0) AS LIKES_TOTALES,
        NVL(G.CANTIDAD_ETIQUETAS, 0) AS CANTIDAD_ETIQUETAS,
        NVL(H.CANTIDAD_ACCESOS, 0) AS CANTIDAD_ACCESOS
FROM TBL_USUARIOS A
LEFT JOIN TBL_PAISES B 
ON A.CODIGO_PAIS = B.CODIGO_PAIS
LEFT JOIN PUBLICACIONES C
ON A.CODIGO_USUARIO = C.CODIGO_USUARIO
LEFT JOIN AMIGOS D 
ON A.CODIGO_USUARIO = D.CODIGO_USUARIO
LEFT JOIN LIKES_PUBLICACIONES E
ON A.CODIGO_USUARIO = E.CODIGO_USUARIO
LEFT JOIN LIKES_FOTOGRAFIAS F 
ON A.CODIGO_USUARIO = F.CODIGO_USUARIO
LEFT JOIN ETIQUETAS_FOTOS G
ON A.CODIGO_USUARIO = G.CODIGO_USUARIO
LEFT JOIN ACCESOS H
ON A.CODIGO_USUARIO = H.CODIGO_USUARIO
ORDER BY A.CODIGO_USUARIO;


SELECT *
FROM VW_USUARIOS;

SELECT *
FROM MVW_USUARIOS;

SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_AMIGOS
FROM TBL_AMIGOS
WHERE CODIGO_ESTATUS = 1
GROUP BY CODIGO_USUARIO;


SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_PUBLICACIONES
FROM TBL_PUBLICACIONES
GROUP BY CODIGO_USUARIO; 


SELECT CODIGO_USUARIO, COUNT(*) AS LIKES_PUBLICACIONES
FROM TBL_LIKE_PUBLICACIONES
GROUP BY CODIGO_USUARIO;

SELECT CODIGO_USUARIO, COUNT(*) AS LIKES_FOTOS
FROM TBL_LIKE_FOTOGRAFIAS
GROUP BY CODIGO_USUARIO;

SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_ETIQUETAS
FROM TBL_ETIQUETA_FOTOGRAFIAS
GROUP BY CODIGO_USUARIO;

SELECT CODIGO_USUARIO, COUNT(*) AS CANTIDAD_ACCESOS 
FROM TBL_HISTORIAL_ACCESOS
GROUP BY CODIGO_USUARIO;

--11. De la consulta anterior cree una vista ma2terializada y utilícela desde una tabla dinámica en Excel
--para mostrar una gráfica de línea que muestre la cantidad de amigos por cada usuario.

